'use client';

import { Zap, Clock, TrendingUp, Calendar, ChevronDown, ChevronUp, RefreshCw } from 'lucide-react';
import type { CacheSummary } from '@/lib/types';

interface Props {
  summaries: CacheSummary[];
  reports: Record<string, string[]>;
  onRefresh?: () => void;
}

const GRAN_CONFIG: Record<string, { label: string; icon: React.ReactNode; color: string }> = {
  hourly:  { label: 'Hourly',  icon: <Clock size={12} />,      color: '#6366f1' },
  daily:   { label: 'Daily',   icon: <TrendingUp size={12} />, color: '#06b6d4' },
  weekly:  { label: 'Weekly',  icon: <Calendar size={12} />,   color: '#8b5cf6' },
  monthly: { label: 'Monthly', icon: <Calendar size={12} />,   color: '#f59e0b' },
};

export default function CacheStatusPanel({ summaries, reports, onRefresh }: Props) {
  const totalReports = Object.values(reports).reduce((a, b) => a + b.length, 0);

  return (
    <div style={{
      background: 'var(--bg-glass)',
      backdropFilter: 'blur(20px)',
      border: '1px solid var(--border-subtle)',
      borderRadius: 'var(--radius-md)',
      padding: 16,
    }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Zap size={14} style={{ color: 'var(--accent-amber)' }} />
          <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)' }}>
            Cache Intelligence
          </span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span className="badge badge-cache">{totalReports} reports</span>
          {onRefresh && (
            <button className="btn-ghost" style={{ padding: '4px 8px', fontSize: 11 }} onClick={onRefresh}>
              <RefreshCw size={11} />
            </button>
          )}
        </div>
      </div>

      {/* Granularity bars */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginBottom: 14 }}>
        {Object.entries(GRAN_CONFIG).map(([gran, cfg]) => {
          const count = reports[gran]?.length ?? 0;
          const max = 10;
          const pct = (count / max) * 100;
          return (
            <div key={gran} style={{
              padding: '10px 12px',
              background: 'rgba(5,5,20,0.4)',
              borderRadius: 'var(--radius-sm)',
              border: '1px solid var(--border-subtle)',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 }}>
                <span style={{ color: cfg.color }}>{cfg.icon}</span>
                <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>{cfg.label}</span>
                <span style={{ fontSize: 11, color: 'var(--text-secondary)', marginLeft: 'auto' }}>{count}/10</span>
              </div>
              <div style={{ height: 3, background: 'rgba(255,255,255,0.06)', borderRadius: 99 }}>
                <div style={{ height: '100%', width: `${pct}%`, background: cfg.color, borderRadius: 99, transition: 'width 0.4s ease' }} />
              </div>
            </div>
          );
        })}
      </div>

      {/* Recent summaries */}
      {summaries.slice(0, 3).map((s, i) => (
        <div key={i} style={{
          padding: '10px 12px',
          background: 'rgba(5,5,20,0.3)',
          borderRadius: 'var(--radius-sm)',
          border: '1px solid var(--border-subtle)',
          marginTop: 8,
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 5 }}>
            <span className="badge badge-cache" style={{ fontSize: 9 }}>{s.granularity}</span>
            <span style={{ fontSize: 11, color: 'var(--text-secondary)' }}>{s.coverage}</span>
          </div>
          <p style={{ fontSize: 11, color: 'var(--text-muted)', lineHeight: 1.5 }}>
            {s.summary.slice(0, 140)}{s.summary.length > 140 ? '…' : ''}
          </p>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginTop: 6 }}>
            {s.metrics.slice(0, 4).map((m) => (
              <span key={m} style={{
                fontSize: 10, padding: '2px 7px', borderRadius: 99,
                background: 'rgba(99,102,241,0.08)', color: 'var(--text-muted)',
                border: '1px solid rgba(99,102,241,0.12)',
              }}>{m.replace(/_/g, ' ')}</span>
            ))}
          </div>
        </div>
      ))}

      {summaries.length === 0 && (
        <div style={{ textAlign: 'center', padding: '16px 0', fontSize: 12, color: 'var(--text-muted)' }}>
          No cached reports yet. Reports are generated by cron jobs.
        </div>
      )}
    </div>
  );
}
